name: breakpoints_utilities
description: Breakpoint utilities for Dart and Flutter projects.
version: 0.0.2

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=3.16.7 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  melos: ^4.0.0
