name: breakpoints_utilities
description: Breakpoint utilities for Dart and Flutter projects.
version: 0.0.2

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.16.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  melos: ^3.2.0
