name: breakpoints_utilities
description: Breakpoint utilities for Dart and Flutter projects.
version: 0.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  melos: ^3.1.1
